default_language_version:
  python: python3.11

exclude: |
  (?x)^(
    atxpylib/.* |
    atxdispatch/static/(?!script.js).* |
    dev_data/.* |
    migrations/.* |  # generates non-pep8-compliant code
    tests/assets/.*
  )$

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.2
    hooks:
    - id: ruff
      args:
        - "--fix"
#        - "--unsafe-fixes"
    - id: ruff-format

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-use-fstring==1.4
        - flake8-type-checking==2.9.0

  - repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks:
      - id: standard

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: pretty-format-json
        types:
          - file
        files: \.(json)$
        args:
          - "--autofix"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
        exclude: "tests/.*(?:fixtures|utils)\\.py"
        args:
          - "--pytest-test-first"
      - id: trailing-whitespace

#  - repo: local
#    hooks:
#      - id: mypy
#        name: mypy
#        entry: scripts/run-mypy.sh
#        language: system
#        pass_filenames: false
#        types:
#          - python

#  - repo: local
#    hooks:
#      - id: tests
#        name: tests
#        entry: ./tests.sh
#        language: system
#        pass_filenames: false
