exclude: |
  (?x)^(
    tests/assets/.*
  )$

repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/standard/standard
    rev: v17.1.2
    hooks:
      - id: standard

#  - repo: local
#    hooks:
#      - id: tests
#        name: tests
#        entry: ./tests.sh
#        language: system
#        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/google/osv-scanner
    rev: v2.2.4
    hooks:
      - id: osv-scanner
        args:
          - "-r"
          - "."
