# i had to add this to make cargo resolver msvr-aware and therefore respect the 1.77 version i'm stuck with because of windows 7
[resolver]
incompatible-rust-versions = "fallback"

#[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-linux-gnu-ld"
#linker = "aarch64-linux-gnu-gcc"
